apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-service-app
spec:
  selector:
    matchLabels:
      app: employee-service-app
  template:
    metadata:
      labels:
        app: employee-service-app
    spec:
      containers:
      - name: employee-service-app
        image: denizkpln/dk-employee-service
        ports:
        - containerPort: 8001
        env:
        - name: EUREKA_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: eureka-cm
              key: eureka_service_address
        - name: CONFIG_SERVER
          valueFrom:
            configMapKeyRef:
              name: config-cm
              key: config-server      
        - name: DB_HOST
          valueFrom:
              configMapKeyRef:
                name: mysql-cv
                key: db_host
        - name: DB_DATABASE
          valueFrom:
              configMapKeyRef:
                name: mysql-cv
                key: database
        - name: DB_USERNAME
          valueFrom:
              secretKeyRef:
                name: sc-mysql
                key: username
        - name: DB_PASSWORD
          valueFrom:
              secretKeyRef:
                name: sc-mysql
                key: password 
---
apiVersion: v1
kind: Service
metadata:
  name: employee-service-svc
spec:
  selector:
    app: employee-service-app
  ports:
  - port: 80
    targetPort: 8001
        
