apiVersion: v1
kind: Secret
metadata:
  name: sc-mysql
type: Opaque
data:
  username: cm9vdA==
  password: c2FzYQ==

---

apiVersion: v1
kind: Secret
metadata:
  name: sc-postgre
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: c2FzYQ==





