apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registry-app
spec:
  selector:
    matchLabels:
      app: service-registry-app
  template:
    metadata:
      labels:
        app: service-registry-app
    spec:
      containers:
      - name: service-registry-app
        image: denizkpln/dk-service-registry
        imagePullPolicy: Always
        ports:
        - containerPort: 8761

---

apiVersion: v1
kind: Service
metadata:
  name: service-registry-svc
spec:
  selector:
    app: service-registry-app
  ports:
  - port: 80
    targetPort: 8761
