#spring:
#  application:
#    name: gateway-service
#  cloud:
#    gateway:
#      routes:
#        - id: department-service
#          uri: lb://department-service
#          predicates:
#            - Path=/department/**
#        - id: employee-service
#          uri: lb://employee-service
#          predicates:
#            - Path=/employee/**
#      discovery:
#        locator:
#          enabled: true
#  zipkin:
#    base-url: ${ZIPKIN_URI:http://localhost:9411}
#server:
#  port: 8889

#eureka:
#  client:
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
#  instance:
#    prefer-ip-address: true

#eureka:
#  client:
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
#    fetch-registry: 'true'
#    register-with-eureka: 'true'
#  instance:
#    prefer-ip-address: 'true'
#
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#        exclude: info